name: deadlock-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - numpy=2.2.2
  - pandas=2.2.3
  - python-dateutil
  - pytz
  - tzdata

  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - attrs==25.1.0
      - beautifulsoup4==4.13.3
      - bs4==0.0.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - discord==2.3.2
      - discord.py==2.4.0
      - frozenlist==1.5.0
      - idna==3.10
      - multidict==6.1.0
      - propcache==0.2.1
      - python-dotenv==1.0.1
      - requests==2.32.3
      - six==1.17.0
      - soupsieve==2.6
      - typing_extensions==4.12.2
      - urllib3==2.3.0
      - yarl==1.18.3